[project]
name = "reaper-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=7.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
